### ISSUE TITLE
自己手上现有的ESP8266可以刷入固件吗

### ISSUE THREAD

**Issue by hanfengcan** [MiEcosystem/miio_open#1]
自己手上有esp8266,可以刷入固件吗.在GitHub上面没发现有提供源码.后期有考虑开源相关sdk吗.

或者有考虑接受类似于[nodemcu](https://github.com/nodemcu/nodemcu-firmware)这种第三方固件接入吗.

对于独立的个人开发者有相关的支持吗.看文档现在好像面向企业用户的样子

**Comment by MIhanguangyi** [comment]
源码正在整理，会在32平台上开放。请耐心等待，谢谢。第三方固件接入米家协议需要等小米协议完全开放才可以，目前开放平台暂时面向企业开发者。

**Comment by hanfengcan** [comment]
期待,希望后期可以对个人开发者开放

**Comment by mayulin2008** [comment]
期待！

**Comment by Fanhang32** [comment]
@MIhanguangyi ESP32会先开放？大概什么时候？期待！！！

**Comment by kopinions** [comment]
现在是什么情况呢？
