### ISSUE TITLE
02D wifi模块OTA升级遇到两个问题

### ISSUE THREAD

**Issue by xiaoyongge** [MiEcosystem/miio_open#10]
问题一：
![image](https://user-images.githubusercontent.com/12733226/60146229-60e95280-97fb-11e9-9811-1d3f03826d1c.png)
![image](https://user-images.githubusercontent.com/12733226/60146234-66df3380-97fb-11e9-9977-a81603fb2ddf.png)
文档里写调用update_me返回ok/error，但是log返回的是todo。硬件02D wifi模块。
问题二：
![微信图片_20190626101816](https://user-images.githubusercontent.com/12733226/60146305-baea1800-97fb-11e9-8b72-b59200920d8d.png)
OTA升级在30%进度失败了，30%进度是具体哪个位置

**Comment by xiaoyongge** [comment]
![image](https://user-images.githubusercontent.com/12733226/60147389-c8a19c80-97ff-11e9-9edf-ed1e64a781ee.png)
问题二是通过后台下发OTA命令的

**Comment by silentcedar** [comment]
1、update_me指令仅在2.x.x版本中实现，这里建议按照MCU OTA流程，没必要尝试重新传输；
2、30%没有特殊含义，只是代表downloading超时失败

**Comment by xiaoyongge** [comment]
为什么downloading会超时，什么原因导致的？

**Comment by xiaoyongge** [comment]
> 1、update_me指令仅在2.x.x版本中实现，这里建议按照MCU OTA流程，没必要尝试重新传输；
> 2、30%没有特殊含义，只是代表downloading超时失败

为什么downloading会超时，什么原因导致的？
