### ISSUE TITLE
无法正常使用小米模组

### ISSUE THREAD

**Issue by weizhou-chaojixx** [MiEcosystem/miio_open#2]
连接串口后无法启动AP ，显示efuse crc验证失败，也发现接收串口命令。。是不是要重新刷固件还是什么原因？

**Comment by MIhanguangyi** [comment]
请问是否有刷其他固件？模组是小米定制的，需要配套的小米固件。

**Comment by lightless233** [comment]
之前误操作将固件刷掉了，固件被刷掉后还有没有办法刷回小米固件？用的是MHCWB3P mini开发板。
