### ISSUE TITLE
智能锁 蓝牙网关上报开门记录

### ISSUE THREAD

**Issue by Banson-ZHANG** [MiEcosystem/miio_open#8]
固件端的log显示已经开门成功，并推送成功开门记录给网关，插件端查询不到开门记录
log如下，请问怎么样定位这个问题

[I] :  unlock 
[E] : adv len 31, scan len 15
[I] MIBEACON: send mibeacon obj 0x000B
[E] : adv len 18, scan len 0
[I] MIBEACON: no more mibeacon obj.
[I] : Fri Mar 29 02:20:17 2019
[I] : Fri Mar 29 02:20:22 2019

**Comment by linbing1** [comment]
请在智能锁工程或SDK工程中提交issue
