### ISSUE TITLE
BLE 通用属性定义有缺失

### ISSUE THREAD

**Issue by riobard** [MiEcosystem/miio_open#9]
米家蓝牙温湿度传感器（product id 0x01aa）会通过 BLE Advertisement 定期汇报三个通用属性：温度（0x1004）、湿度（0x1006）、电量（0x100a）。

但多数时候它还会汇报另一种通用属性：温湿度（0x100d），格式为4字节（2字节温度+2字节湿度）。在本 repo 对应的[蓝牙通用属性文档](https://github.com/MiEcosystem/miio_open/blob/master/ble/04-米家BLE%20Object定义.md)中缺乏该属性的相关定义和上报给米家服务器的时间间隔，请补充。

**Comment by linbing1** [comment]
现在已经不再支持此属性。也不再允许使用此属性。故文档中没有。

**Comment by riobard** [comment]
那是否应该在文档中说明这种情况并注明 deprecated?
